version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
before_build:
  - nuget restore
build:
  project: Nuget.Link.sln
  verbosity: normal
platform:
  - Any CPU
configuration:
  - Release
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))