version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
build:
  project: Nuget.Link.sln
  verbosity: minimal